zen-browser/www

README.md
src/components/features.tsx

Current:
My fix:
(Also fixed spacing between Floorp and LibreWolf)

Fix spacing of comparison table on mobile

---

src/components/branding-assets.tsx

Fixes the issue in  `\branding-assets` page where the users cannot download the filled versions of the Zen Logo.

fix: Fixed download links for Branding Assets

---

src/components/theme-page.tsx

The sidebar on the theme page was experiencing a layout issue where it would overlap with the footer when scrolling. This bug negatively affected the user experience by disrupting the intended page flow.
- **Sticky Effect Preserved:** The sidebar's `lg:fixed` class was replaced with `lg:sticky`, ensuring that the sticky effect is maintained. This change preserves the sidebar's intended behavior of staying in view while scrolling, but now without the bug where it overlaps the footer.
- **Layout Adjustments:** Additional adjustments to padding and margin were made to ensure the sidebar aligns correctly and the overall layout remains consistent across various screen sizes.
- **Code Cleanup:** Unused imports (`LoaderIcon`, `LoaderPinwheelIcon`, `MoveLeftIcon`) from `lucide-react` were …

fix(theme-page): resolve sidebar overlapping footer issue

---

next.config.mjs
src/app/layout.tsx
src/lib/styled-components-registry.tsx

This fixes `styled-components` styles not rendering on the server side.
Followed this documentation: https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components
For easy debug, disable JS in your devtools and go to `/download`. You should see something similar to this:
(For reference, this was taken on the production website which, from the looks of it, does not load the `styled-component` regardless for some reason?)
Using this fix, it does load the style:
If JS is disabled, you can't fill the form anyway, but this is still useful - it will prevent a partial [Flash Of Unstyled Content](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) when hydrating on the form area, will also improve layout shift, and by extension UX and SEO.

fix: Use NextJS recommended config for styled-components

---

src/components/theme-card.tsx

Renaming the `<ThemeCardWrapepr />` constant to `<ThemeCardWrapper />`

fix: CardWrapper typo

---

src/components/download.tsx

Fixing the capitalization of AArch64 as mentioned in #91

fix: Corrected capitalization of AArch64

---

src/components/features.tsx

This addresses #93
The styling for ultra-wide monitors can be fixed by simply adding a max-width to the `Features` component. 
<figure>
<figcaption>Styling of the features before</figcaption>
</figure>
<br><br>
<figure>
<figcaption>Styling of the features after</figcaption>
</figure>

fix: Formatting of features.tsx on ultrawide monitors

---

src/components/features.tsx

Fixing the styling issues when a user opens the site on a medium width desktop browser. 
Currently making each section half of their parent div on **large** windows is done by manually setting `md:w-1/2` on each section. 
The issue with this is that on medium windows the width is still half and the styling breaks. This could be fixed by changing `lg:w-1/2` but a more elegant solution is to set each child to `flex-1` so they both have equal... growing ability?... flex priority?... idk. Basically, it gives them both the same amount of entitlement to the available space. 
Before Large Window:
Before Medium Window:
After Large Window:
After Medium Window:
Split view container was set to `lg:mx-auto` on the split-views container but was just `mx-auto` on all the others
Before:
After:

fix: Responsive design on medium windows

---

messages/README-LANGUAGES.md
messages/de.json
messages/en.json
next.config.js
package-lock.json
package.json
src/app/layout.tsx
src/components/navigation.tsx
src/i18n.ts

Hi, 
#129
Here is a proposal for how to setup multi-language support using [next-intl](https://next-intl-docs.vercel.app/docs/getting-started/app-router/without-i18n-routing). I set it up to go based off of the browser settings (which reads the 'accept-language' http request header). Right now, I just made it change the navbar text because to support multi-language support, **every single bit of english** on **every page** in **every component** has to be written down in a `en.json` like ...
```json
{
"home-page": {
"home-hero-text": "Zen is the best way to browse the web.",
"home-hero-subtext": "Beautifully designed, privacy-focused, and packed with features. We care about your experience, not your data.",
```
... then referenced in the html tag like ...
```jsx
import { useTranslations } …
```

feat: Multi-language support

---

src/app/globals.css

Smooth scrolling wasn't working due to the `scroll-behavior` being under body, not html. This commit moves it to html and makes it in Tailwind CSS format.
https://github.com/user-attachments/assets/fdc62867-d76e-4d9b-8f08-3368c6a3a33d

fix: Smooth scrolling

---

src/components/download.tsx

Change the button text for installation instructions for Mac

---

src/app/feed.xml/route.ts

Not sure why the RSS feed endpoint was deleted in commit 406ff44 but it broke my (and presumably others) feed readers. This commit re-adds it back. If it was removed on purpose, then [the meta tag in layout.tsx](https://github.com/zen-browser/www/blob/48a96ee010d01c6cfa0ddc5897cb84bc9f84db72/src/app/layout.tsx#L27) should also be removed or otherwise adjusted so that feed readers for new users don't find and try to add broken links. The `/feed.xml` endpoint is (or should be) statically built, and so any future accesses once a site build has gone live should be instant and and pulled from a cache rather than be recomputed.
I noticed that localization attempts were going on. While I agree that it should happen, unless the Release Notes object also get localized, the `/feed.xml` endpoint …

fix: Re-add RSS 2.0 Feed

---

src/app/globals.css

In Firefox dark mode, when the user selects text, it becomes hidden.
I'm not sure which style you prefer or the best way to specify the `::selection` style class in your setup, but here's a PR that uses the primary color to make the selected text more contrasting.
Issue:
Suggested solution:

style: fix text selection color in Firefox dark mode

---

.gitignore

I'm using WebStorm, and my editor was notifying me about committing config files while I was "working" on a style fix. I think it's best practice not to commit IDE and backup files, so I added those to the `.gitignore` list.

chore: git ignore IDE config

---

src/components/features.tsx

Fixed a typo I noticed when I was reading the webpage.

Fix typo "is it firefox based?" -> "Is it Firefox based?"

---

src/app/privacy-policy/markdown.css
src/app/privacy-policy/page.tsx

- Reduced top and bottom margins on #policy to minimize empty space between navbar and content.
- Adjusted heading margins for better spacing consistency.
- Added responsive adjustments for smaller screens.

Reduce margin and adjust spacing for Privacy Policy and About pages

---

package.json
src/components/mode-toggle.tsx

- Remove system theme option
- Refactor ModeToggle component for immediate theme switching
- Implement local state management for smoother transitions
- Persist theme preference in localStorage
- Update icon display logic for better visual feedback
This commit addresses the issue of delayed theme switching and simplifies the user experience by offering only dark and light modes.

fix:Simplify theme toggle to dark/light only

---

src/app/release-notes/page.tsx

Minor tweak to the 'header' container padding when viewing at `XL` width, as it previously didn't have any before. Have also updated the `LG` value to 10 as well so the padding is more consistent across different breakpoints.
Before:
After:
Let me know what you think! ❤️

fix: Release notes header `XL` padding

---

src/components/features.tsx

Earlier the feature is default to open first item with corresponding images
Now I have made it to default close and when closed the corresponding image will be all three 
Since the images impact more than the text users if sees images first may tend to look into it.
Also an active dropdown looks a little unorganized for a new page.
Do let me know what you'll think

Improved the FAQ section

---

src/components/download.tsx
src/components/ui/copy-button.tsx
src/lib/hooks.ts

I suggest adding a 'Copy to Clipboard' button for scripts. Additionally, I would like to implement a toast notification upon copying, but I am unsure if there are any existing designs for it. Another enhancement I propose is adding a script for Flatpak installation similar to the one you have for AppImage installation. If you approve of these suggestions, I can implement them in this PR.
After copy button click check icon is shown for 3 sec

Clipboard copy button

---

src/app/feed.xml/route.ts

This updates the RSS feed to match the releases page by adding the Theme Changes section, re-ordering the sections to match, adding issue numbers to the issues list and adding the release image.

Update RSS feed to match Release Notes page.

---

src/components/cool-header-text.tsx

This could be some firefox's aa bug, however this bugged outline is caused by [color stop](https://tailwindcss.com/docs/gradient-color-stops) .

fix: gradient text outline bugged in firefox

---

src/components/download.tsx

In the case of an unsupported OS, if you don't select an OS version, you will be given a download option that doesn't work.
https://github.com/zen-browser/www/issues/210#issue-2564650745

fix: download option for unsupported OS

---

src/components/footer.tsx

There is no gap between the social icons and the text.
Screenshot of Issue:
If this lack of spacing was not intentional, this pull request will resolve it by adding the necessary gap.
Screenshot of Fix :
Additional Comments: If the lack of spacing was intentional, feel free to disregard this pull request.

fix: margin between socials and text

---

src/lib/themes.ts

Refactored getThemesFromSearch() to make the function more concise and readable. Allows for future expansion on the function without cluttering things up too much.

Refactor getThemesFromSearch() to make more concise and readable

---

src/components/theme-card.tsx
src/components/ui/card.tsx

- Refactored `theme card` to:
- Use `Next/Link` for better accessibility
- Use the shadcn `Card` component

Refactor `theme card` to use `Next/Link` and `Card` component

---

src/components/marketplace.tsx

I found two UI bugs that could potentially cause a page crash and fixed them:
- Prev/Next navigation link is clickable even when disabled
- `CurrentPage` exceeding limit when toggling filters
**Before**
https://github.com/user-attachments/assets/bc92de8e-cbde-46f0-aafe-78a03549c5e1
**After**
https://github.com/user-attachments/assets/ffa88dbc-885a-4345-87aa-2a9e975fc7cf
**Before**
https://github.com/user-attachments/assets/c9c805cb-4035-4263-a14d-1e0cfc1c113c
**After**
https://github.com/user-attachments/assets/4785ca37-743d-4ed0-b50c-713b5badbb60

Fix 2 UI bugs on the Mods page

---

src/app/layout.tsx
src/components/mode-toggle.tsx

Fix #265 
- Simplify the theme toggle logic (by removing the use of `mounted` & copied from [shadcn/ui](https://github.com/shadcn-ui/ui/blob/3259fb7ca165b0ae11124257a20b71001049ecca/apps/www/components/mode-toggle.tsx)).
- Follow the system color preference until the user interacts with the toggle.
- Fix the navigation items flashing when toggling the theme by disabling the transition.
https://github.com/user-attachments/assets/60572f0b-bedb-4c60-afad-706a52a9a4b7
https://github.com/user-attachments/assets/0b6263f3-5162-4395-a372-5c330bdd38d0

Theme toggle improvements

---

src/components/go-back.tsx
src/components/marketplace.tsx
src/components/theme-page.tsx

This will allow visitors to go back to the previous page by clicking on the "go back" link.
Previously, the link always sent users to /mods page which would reset all of their filtering, sorting and the page count.

Added a go back link that would keep previous search params

---

src/app/layout.tsx

This PR fixes a minor UI bug that caused a flash when the theme was set to 'dark' (or when the system theme was in dark mode) because the body didn't have a background set.
https://github.com/user-attachments/assets/66fbd084-ff45-4a90-b006-0fe36db56932
https://github.com/user-attachments/assets/29f76503-fb76-4f05-9209-1e5dd0881aed

Fix screen flashes when the page loads in dark theme

---

src/lib/release-notes.ts

The variable is probably not spelled '--zen-main-browser-backgrond'. This adds the letter `u` to spell 'background'.

Spelling correction for release note theme change

---

src/components/header.tsx

Previously, if user is on a phone `about` and `your` did not have a whitespace in between.
I have fixed tis.

Fix text wrapping in header

---

src/components/faq/faq.tsx

Very small commit but I was reading the homepage when I noticed. The way the sentence is worded makes it seem like Zen is the only browser with HTTPS support, where it is supposed to be about Zen having a HTTPS-only mode.

fix(faq): Unclear sentence about HTTP-only mode

---

src/lib/mods.ts

This pull request makes the search bar on /mods search both title and description.

Feat: search description and title when searching for mods

---

package-lock.json
package.json
src/app/layout.tsx

This PR should fix the screen flash on page load when using dark theme.
Site seems to use, according to Wappalyzer, Cloudflare Rocket Loader which blocks the blocking script from next-themes. 
I'm updating package and adding a prop based on next-themes docs https://github.com/pacocoursey/next-themes#using-with-cloudflare-rocket-loader
https://github.com/user-attachments/assets/8b3c7b17-4e47-495d-a59b-c881ef13cf71

Fixing screen flash when using dark theme 

---

src/lib/release-notes.ts

Corrects a typo in the release notes referencing https://github.com/zen-browser/desktop/pull/3194.

fix: typo in release note

---

src/components/download/download.tsx

This pull request fixes three problems on the download page when going back and switching the platform after selecting a linux download type.
1. When selecting Flatpak, then switching to Windows (optimized), the warning "Flatpak will install the Generic version" still shows up.
2. When selecting Flatpak, then switching to either Windows or MacOS, the actual file that is downloaded is the Flatpak version.
3. When selecting either Flatpak or AppImage, then switching to another platform, the page after clicking on Download contains a box explaining how to install the AppImage/Flatpak version using the command line.
All of these problems are caused by the code checking whether the selected download type is Flatpak/AppImage but not whether the current platform even is Linux.

Fix(download): problems with switching platforms

---

src/components/themes-search.tsx

Fix #292: Zen Mods Page removes order filter after "Go Back" is pressed.
Changes made:
Added logic to listen for browser navigation events (`popstate`).
Updated the order filter dynamically based on the query parameters when navigating back, ensuring that the filter state is preserved.

fix: #292 preserve order filter when navigating back on Zen Mods Page 

---

src/components/download/download.tsx
src/lib/releases.ts

* Fixes #305  Zen Twilight link for macOS x86_64 is broken
* added new entry MacOSIntelTwilight to handle the intel release target

fix : Zen Twilight link for macOS x86_64 is broken

---

src/pages/about.astro
src/pages/donate.astro
src/pages/index.astro
src/pages/release-notes/index.astro

Revised page titles to improve branding and user experience:
- Updated `/title` from "Welcome to Zen" to "Zen Browser"
- Updated `/release-notes` title from "Release Notes" to "Release Notes
- Zen Browser"
- Updated `/donate` title to "Donate - Zen Browser"
- Updated `/about` title to "About - Zen Browser"
Enhances consistency and SEO across key pages

feat(seo): update page titles for website

---

src/pages/about.astro
src/pages/donate.astro
src/pages/download.astro

This fix removes the use of "h-screen" for setting the height of the page to screen, which causes clipping behaviour on small and large viewports. Replaced with the use of margins.
Example of old using devtools to push the content:
New:
This fix is applied to the pages: "Download", "About Us", and "Donate".

fix: fixed spacing for multiple pages being cut off on device screens

---

src/components/NavBar.astro

fix: adjusted toggle theme button to prevent clipping of the download button on mobile

---

src/components/Hero.astro

fix: adjusted sizing of "beta out now!" hero label for mobile

---

astro.config.mjs

problem: we don't have 'site' config in astro config. this makes Astro.url.origin API function render localhost in production.

fix: adds site config

---

tailwind.config.mjs

Tailwind dark mode was not correctly set up, this was causing the `dark:` styles to not be applied correctly.
[Tailwind docs](https://tailwindcss.com/docs/dark-mode#customizing-the-selector)

fix: tailwind config dark mode detection

---

src/components/Hero.astro

This way, the user will feel more connected to the word **_`calmer`_** while reading the heading. Currently, the capital **`W`** in **`Welcome`** is drawing attention away from it.

Lowercase Hero Heading

---

src/components/ReleaseNoteItem.astro

This change removes setting "name" prop for the AccordionItem component. The upstream component binds the "open" state to it, so you can only have one accordion of each name open at a time. The current approach is wonky because it means that we can't open two "Fixes" accordions across different versions, because we create the same accordion name across different versions.

feat: allow opening multiple accordions of the same name

---

astro.config.mjs

Since `/themes` was changed to `/mods`, I've frequently come across links to the old path that now lead to a 404. This PR adds a redirect from `/themes` to `/mods` to keep those old links functioning!

fix: redirect old /themes URLs to new /mods

---

src/components/ModsList.tsx
src/hooks/useModsSearch.ts

I've added a simple pagination and search param to the mods page.

Add pagination and search param for mods page

---

src/components/ModsList.tsx

I have fixed the layout of mods page's filtering by changing to `grid`.
I've also fixed select input font color so it is visible in dark mode.

Fix layout broken in mobile view

---

src/pages/about.astro

Before:
After:
Changes:
- Added spacing between the colons ( : ) between the names of main team and their descriptions.
- Removed italics and added underline to everyone else. I questioned why there was italics but then realized it's probably because the people in italics didn't have an href to their name. Thus, I opted to remove the italics and add underlines for all the people that did have hrefs.
- Increased spacing between names of main team.
- Increased top margin on contributor images to add extra spacing.

feat: cleaned up the community page

---

src/layouts/Layout.astro
src/pages/index.astro

This is a fix to #436 which adds a schema to improve SEO.
Closes #390
```tsx
const onHomepage = Astro.url.origin === 'https://zen-browser.app/'
```
This does not work on Astro as it builds on server, which does not have the domain as its url origin.
I have fixed it to be an optional boolean prop which can be passed from `index.astro`.

Actually inject the schema to homepage on build

---

src/layouts/Layout.astro

Adding `data-cfasync="false"` will make rocket loader ignore this script according to their docs.
This should fix the theme script being deferred on load until page has fully loaded by cf.
Source: https://developers.cloudflare.com/speed/optimization/content/rocket-loader/ignore-javascripts/

Make cf rocket loader ignore theme script

---

src/components/Hero.astro

Changes Made:
- Removed the "Beta is now available!" link to simplify the hero interface.
- Updated the download button text to read "Beta is now available!" or "Join beta now"
- The Download option remains in the navbar.
This update enhances user experience by focusing on clarity and removing unnecessary information.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fix(hero): update download button text to reflect beta availability

---

src/components/ModsList.tsx

clicking the Back button on the Mods page (specifically on page 2) incorrectly redirects to the homepage instead of the previous page (Page 1)

 Fix issue with back button on Mods page 

---

src/pages/download.astro

tarball for twilight releases was changed on github, this reflects that. flathub doesn't have a twilight version, so this is removed.

fix: fixed twilight tarball download and removed flathub option

---

src/release-notes/stable.json

The current [workflow run](https://github.com/zen-browser/desktop/actions/runs/13184385191) link in the release note of the latest version leads to a 404 page. I changed it with the one triggered on commit e353d48, which is tagged 1.7.5b now.

Fix the github workflow ID of 1.7.5b in release note

---

src/components/Community.astro
src/components/Features.astro
src/components/Hero.astro

This PR fixes the "Explore Zen" button on the Hero section of the home page. For some reason, the ID of the "Features" section was set to "Community", which is already the ID for another section.
I've also fixed some grammar on the Community section.

Fixes "Explore Zen" hero button and some language

---

src/components/Button.astro
src/components/Features.astro
src/layouts/Layout.astro
tailwind.config.mjs

I've replaced the almost invisible background color for buttons with a subtle one which is the same as `feature.astro` section.
To change the color, just edit the values in the `layout.astro`.
Before:
Now:

Replace the bg for buttons with a subtle background color

---

src/components/Hero.astro

I've added a space after `features.` and changed `<br />` to show from `sm` instead.

Fix missing space in hero description

---

src/pages/release-notes/index.astro

Closes #526
This PR adds a button which expands and collapses every "Fixes", "Features", "Theme Changes" and "Breaking Changes" accordion in the release notes page.
Before:
After:

Add button to expand/collapse every accordion in release notes

---

src/components/ModsList.tsx

Fixes #531 
By using buttons that calling `setPage` directly  instead of anchor tags, the state is persisted correctly when navigating between pages. 
Video demonstrating fix:
https://github.com/user-attachments/assets/1954f0c7-bc05-4a45-89cf-d2392e5c5fb6

Use buttons instead of anchor tags on mods list page

---

src/components/Features.astro
src/pages/welcome.astro

The *Features* section and the new *Sponsors* section were placed alongside each other on large screens.
<details>
<summary>Initial Layout</summary>
</details>
- Places the Sponsor section below the Features section, with reasonable spacing between them.
<details>
<summary>Updated Layout</summary>
</details>
Tries to fix #527 
I am unsure whether the initial layout was intentional (maybe for sponsor visibility?). In that case, additional layout changes would need to be made to have a consistent look with the side-by-side sections.
P.S. The above screenshots are in 1536x864 for demonstration purposes. The initial layout looks kind of alright in 1920x1080.

Fix layout on welcome page

---

src/pages/mods/[...slug].astro

Since the mods page does not show much useful information about individual mods, it might be useful for most users to be able to visit the mods' homepage and view the details before installing. Mod home page links are already optionally available in [`ThemeAPI`](https://github.com/zen-browser/www/blob/20e516f62abe4db7c541e189b6a67bbb8dd987d7/src/mods.ts#L3C18-L18).

feat: include mod homepage link

---

src/components/Features.astro
src/components/Footer.astro
src/components/ReleaseNoteItem.astro
src/layouts/Layout.astro
src/pages/about.astro
src/pages/download.astro
src/pages/mods/[...slug].astro
src/pages/privacy-policy.astro
src/pages/release-notes/index.astro

This PR unifies hyperlinks on plaintext throughout the website. The current website uses a mix of coral text and just an underline depending on where you look. The privacy policy and release notes use coral text while the mod page, download page, and contributor page use just an underline.
1. Creates a universal 'zen-link' class that applies 'text-coral underline underline-offset-4' classes.
2. Applied this class to all the necessary areas in the website. The only elements it doesn't apply to are the logo at the top-left, image redirects and buttons, of course. Any other usage of plaintext hyperlinks have the 'zen-link' class.
The PR also adjusts the spacing on the mod slug page of the info section:
(old)
(new)
here are some images of the hyperlink changes throughout the site:
The main …

Plaintext link theming unification & misc

---

src/components/Video.astro

Because of how astro work, DOMContentLoaded did not run properly on some browsers.

Fixed video not loading properly on some browsers

---

src/pages/download.astro

Updated the download.astro page to make platform compatibility and installer choices clearer for non-technical users. Reworded text for macOS, Windows, and Linux sections.

docs(download): clarify OS requirements and installer choices

---

src/components/ModsList.tsx

This fixes a change introduced in #512 where image containers for the mods page was set to "h-auto". The contributor intended this for ultra-large screens, which you can't see the issue on, but you see it on regular screens:
Above is the current live site. Notice the first mod in the list has a smaller, inconsistent image height. In the PR that made this happen, the contributor probably didn't check for regular screens, because using "h-auto" here wouldn't show this behavior on ultra-large screens. It's not visible in the screenshot above, but most of the heights are actually inconsistent. Some are a few pixels off, others are almost a hundred pixels off. Here's what this PR looks like:

fix: fixes inconsistent mod item image height

---

src/animations.ts

Improve LCP by making the LCP element technically (but not-visibly) opaque. This avoids LCP calculations waiting on the animation to play.
New (511.4 ms)
Old (3,322.9 ms)
This isn't a "real performance improvement", but fixes the animation blocking the metric. There are other improvements to be made for LCP, but with this change we can understand if LCP is actually an issue for users, or not.

Improve LCP by making element slightly opaque

---

src/pages/release-notes/index.astro

Fixes two things:
1. The "Back to the top" button was using opacity to show/hide itself. This just meant that the button was invisible, but not actually hidden. So it meant you could click or hover it while it was invisible.
2. Applied theming to the version selection modal.
Before:
After:

Release note minor design fixes

---

src/components/Hero.astro

So, I opened the website and saw this giant gap between "calmer" and "internet":
Looking into the codebase and figured out that it happens because of code formatting, so according to the similar solution in "Features", I made changes in Hero
Result:

Fix Hero component text

---

src/components/SocialMediaStrip.astro

Just a small nitpick I noticed while surfing the site, updated the Font Awesome icon from twitter to x-twitter in the social media strip to reflect the current branding of the X platform.

chore: update twitter icon to x icon in social media strip

---

src/release-notes/stable.json

Going forward I'll remove the "Fixed" at the start of sentences because the updated Release Notes design has the "Fixed" indicator to the left, which makes it look weird seeing two "Fixed". I'll also be keeping full stops at the end of sentences as well.

1.12.5b & 1.12.6b grammar release notes

---

.github/workflows/biome-autofix.yml

I have fixed how the biome autofix workflow was set to master instead of main.

fix(workflow): update references from master to main in biome-autofix.yml

---

src/release-notes/twilight.json

Changed "mroe" to "more" in twilights release notes

fix: spelling mistake in twilight release notes

---

.github/workflows/ci-pipeline.yml
.gitignore
lefthook.yaml
package.json
playwright.config.ts
src/components/Sponsors.astro
src/components/download/release-data.ts
src/pages/[...locale]/download.astro
turbo.json

I have improved ci pipeline and lefthook overall performance.

chore(ci): enhance CI pipeline with playwright container and adjust job dependencies

---

src/components/download/DownloadScript.astro

Linux is available on some Chromebooks, so is probably the better choice

fix: Chrome OS only offered Mac download

---

src/i18n/en/translation.json

Fixed a typo on the homepage sponsors section.
Before: "donating us directly"
After: "donating to us directly"
Closes #781

docs(www): fix homepage typo (closes #781)

---

src/i18n/en/translation.json

fix: changed the description of the text to be grammatically correct.

fix: correct grammar in sponsors description - change 'donating us directly' to 'donating to us directly'. (#781)
