zen-browser/www

src/components/download.tsx

Changed for more clarity and to keep pace with upcoming apple silicon chips

change "m1 or m2" to "m series chips"

---

package.json
src/app/page.tsx
src/app/release-notes/[version]/page.tsx
src/app/release-notes/page.tsx
src/components/download.tsx
src/components/features.tsx
src/components/footer.tsx
src/components/header.tsx
src/components/logo.tsx
src/components/navigation.tsx
src/components/release-note.tsx

repaired the hydration issue in download page also have improved Image and Links with default next js components 💯

improved ui performance with default next js functions 

---

src/components/ui/blur-fade.tsx

creating this pull request because previous one #8 got failed while compilation

minor commit

---

src/components/release-note.tsx

download button on the release page at center

download button at center

---

src/app/privacy-policy/page.tsx

Replace 'Police' with 'Policy'.

Fix 'police' typo

---

src/lib/release-notes.ts

Feel free to suggest any changes

chore: added v23 release notes

---

.gitignore
src/components/download.tsx
src/components/feature.tsx
src/components/features.tsx
src/components/header.tsx

Minor changes about font size and div spacing

Www responsive

---

src/lib/release-notes.ts

Feel free to add something to the extra notes

v25 release notes 

---

.gitignore
package-lock.json
package.json

- add lock for one package manage. Cause each time someone will clone the repo he/she will need to recreate the lockfile.
- add `--turbo` to use turbopack on dev env
- add default engine to ensure everyone use right runtime

build: clean

---

src/lib/release-notes.ts

v28 release notes

---

next.config.mjs
src/components/theme-card.tsx
src/components/theme-page.tsx

- Optimize your Tailwind CSS code by removing redundant ‘relative’ class elements. 🛠️🤖
- Added width and height to the <Image> component for better optimization.
- Updated useEffect dependency to include 'theme' to trigger updates when theme changes.

refector: Add useEffect dependency and optimize the tailwindcss

---

next.config.mjs
src/components/theme-card.tsx

1. Reduce your Tailwind CSS code by eliminating repetitive elements such as ‘hover: shadow-lg’ and ‘hover:border-blue-500’. 🎯
2. The ‘next/image’ component in Next.js optimizes images without compromising on quality, resulting in an enhanced visual experience for the user. 📷✨
3. also update the next.config.mjs => 
```
images: {
remotePatterns: [
{
protocol: 'https',
hostname: 'raw.githubusercontent.com',
},
],
},
```

refactor: Improved image loading and optimization

---

src/components/features.tsx
src/components/release-note.tsx

Hi!
Some Download buttons on the website were not linked to the download page and pressing them would do nothing.

Fix Downlaod buttons not going to /download

---

src/components/features.tsx

fix: Fix grammar in features

---

src/components/download.tsx
src/lib/db.ts
src/lib/releases.ts

This PR refactors the `DownloadPage` component to enhance platform detection, improve UI elements, and streamline the download flow. The changes include:
1. **Platform Detection**: Improved platform detection logic using `useCallback` and `useEffect` hooks.
2. **UI Enhancements**: Updated the UI for platform selection, architecture selection, and download options with better styling, animations and Fix Layout Shifts.
3. **Download Flow**: Simplified the download flow logic and added confetti animation upon successful download.
4. **Code Cleanup**: Removed redundant code and improved readability.
- Added `detectPlatform` function using `useCallback` to detect the user's platform based on the user agent.
- Updated `useEffect` to call `detectPlatform` on component mount.
- Updated …

refactor: Improved platform detection, UI enhancements, and overall code quality

---

src/components/download.tsx
src/lib/db.ts
src/lib/releases.ts

Revert "refactor: Improved platform detection, UI enhancements, and overall code quality"

---

README.md

fix: README.md image src

---

src/components/features.tsx

Fixing small typos.
| Before | After |
|----------|----------|
| Automated  Releases, to prove security | Automated Releases to ensure security |
| Comunity | Community | 
| Comming Soon | Coming Soon |
| Security And Privacy... | Security and Privacy... |
| zen | Zen |

fix: Minor typos

---

.prettierrc
package-lock.json
package.json

Introduced automatic Tailwind CSS class sorting using Prettier. This feature ensures that Tailwind classes are consistently ordered, improving readability and reducing potential merge conflicts.
For more details on this feature, you can refer to the [Tailwind CSS blog post](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier).
Note: This update will require formatting every .jsx file once to ensure they all follow the new rules. 👾

feat: add Tailwind Prettier sorting configuration

---

src/components/download.tsx

It shows the download is successful while the download starts in a while. This PR aims at fixing the message.

Minor ~ Update the download message

---

src/components/mode-toggle.tsx

Just cleaning up the code in the mode-toggle.tsx cause it has some imports that are never used and an unnecessary console.log()

refactor: Remove unused imports and unnecessary console log

---

src/app/not-found.tsx

feat: designed not found page

---

package-lock.json
src/app/layout.tsx

fix: Navbar Position is fixed for every page mt-5

---

package.json
src/components/cool-header-text.tsx
src/components/release-note.tsx
src/lib/release-notes.ts

- Added `format` script.
- Formatted repo.

feat: Add format script

---

src/components/create-theme.tsx
src/components/features.tsx
src/components/footer.tsx
src/components/marketplace.tsx
src/components/navigation.tsx
src/components/themes-search.tsx

themes -> mods

---

src/components/features.tsx

Changed buttons to links so they work when JS is disabled.

Fixed #188

---

src/components/release-note.tsx

Fixed #204 by disabling sticky scroll on screens smaller than 1024px

Fixed #204

---

src/components/release-note.tsx

Fixed release notes date alignment

---

src/components/download.tsx

@Vigneshk5 How's about this solution?

Fixed #216

---

.eslintrc.json
package-lock.json
package.json
src/app/branding-assets/page.tsx
src/app/create-theme/page.tsx
src/app/download/page.tsx
src/app/layout.tsx
src/app/page.tsx
src/app/privacy-policy/page.tsx
src/app/release-notes/[version]/page.tsx
src/app/themes/[theme]/page.tsx
src/app/themes/page.tsx
src/app/welcome/page.tsx
src/components/create-theme.tsx
src/components/download.tsx
src/components/features.tsx
src/components/footer.tsx
src/components/header.tsx
src/components/logo.tsx
src/components/marketplace.tsx
src/components/mobile-nav.tsx
src/components/navigation.tsx
src/components/theme-card.tsx
src/components/theme-page.tsx

I added eslint rule and ran lint on project, so this pr has so many changes.

Added eslint-unused-imports plugin

---

src/components/mobile-nav.tsx
src/components/mode-toggle.tsx

Added theme toggle to sidebar on mobile view

---

src/components/download.tsx

If the text is not correct, suggest another one, I'll change

Fixed-#220

---

package-lock.json
package.json
src/components/alert-modal.tsx
src/components/download.tsx

As white text is not really noticeable, I changed it to yellow

Flatpak warning

---

src/app/download/page.tsx
src/components/download/appimage-installer.tsx
src/components/download/architecture-card.tsx
src/components/download/architecture-select.tsx
src/components/download/download.tsx
src/components/download/downloaded-header.tsx
src/components/download/flatpak-installer.tsx
src/components/download/form.tsx
src/components/download/linux-installer.tsx
src/components/download/mac-architecture-card.tsx
src/components/download/platform-card.tsx
src/components/download/platform-select.tsx
src/components/download/tools/throw-confetti.ts
src/components/download/types/index.ts
src/components/download/windows-installer.tsx

Refactored download component a little, destructurized this big component. But this page contains a lot of logic and a lot more refactoring have to be done

Refactored download component

---

src/components/download/appimage-installer.tsx
src/components/download/download.tsx

Fixes #219

---

src/lib/themes.ts

- You can now Filter on "Creation Date" and "Updated Date"
- Main Changes in \src\lib\themes.ts

Fixed Filtering Options

---

src/components/marketplace.tsx
src/components/theme-card.tsx

fixed some minor styling issues and inconsistencies

fix minor styling issues

---

src/components/ui/select.tsx

I have fixed the select menu not working on mobile.

Fixed the select menu not working on mobile

---

src/components/marketplace.tsx
src/components/themes-search.tsx

- You can now select a certain amount of mods to be shown
Showcase here:
https://zen-browser-www.pages.dev/mods

Added Pagination

---

src/app/layout.tsx

Changed the title to `Zen Browser`

Changed Title

---

src/components/marketplace.tsx
src/components/theme-card.tsx
src/lib/hooks.ts
src/lib/mods.ts

- **theme-card**: Changed cursor behavior on hover by adding the `cursor-pointer` class.
- **useMarketplace**: Improved maintainability by abstracting 100+ lines of logic from MarketplacePage into a reusable hook, allowing better separation of concerns between UI and business logic.
- **theme-card**: Extract inline `onMouseDown` handler to improve readability. Moved the function to a separate handler named `handleMouseDown`.
- **marketplace**: Replace `useRef` with `useState` for `selectedTags` to improve state management and reactivity.
- **marketplace**: Improve side effects for pagination and theme loading by moving `currentPage` clamping logic to a dedicated function and optimizing `useEffect` for `loadedThemes`.
- **marketplace**: Extract MarketplacePage logic into custom hook …

Refactor Marketplace and Theme Components, Improve State and URL Handling

---

src/app/about/page.tsx
src/app/branding-assets/page.tsx
src/app/create-theme/page.tsx
src/app/download/page.tsx
src/app/layout.tsx
src/app/mods/[theme]/page.tsx
src/app/mods/page.tsx
src/app/page.tsx
src/app/privacy-policy/page.tsx
src/app/release-notes/[version]/page.tsx
src/app/release-notes/page.tsx
src/app/welcome/page.tsx
src/components/download/download.tsx
src/components/features.tsx
src/components/header.tsx
src/components/marketplace.tsx
src/components/navigation.tsx
src/components/release-note.tsx
src/components/welcome.tsx

I have improved height of the layout.tsx.
I have made this change because some pages with less contents (e.g. welcome and download) had too much space vertically which we could have easily filled with the footer that was hidden until scrolled.

Improve height in layout to reduce empty spaces

---

src/components/marketplace.tsx
src/components/themes-search.tsx
src/lib/hooks.ts
src/lib/mods.ts

I have fixed the issue where sorting currently not working until a tag is selected.
I have also made all tags that are in mods list to show as filter option.

Fix sorting not working without tag selected

---

src/components/marketplace.tsx

I have replaced the word `themes` to be `mods` for empty state and hidden pagination if no results.

Change word `themes` to `mods`

---

package-lock.json
package.json
src/components/marketplace.tsx
src/components/theme-page.tsx
src/components/themes-search.tsx
src/lib/hooks.ts
src/lib/mods.ts

I have added a button to sort mods by ascending or descending order.
I have also made slight improvements to the sidebar of the sticky box theme search for better responsiveness.

Implemented a way to sort mods by asc or desc

---

package-lock.json
package.json
src/app/layout.tsx

Revert "Fixing screen flash when using dark theme "

---

src/pages/donate.astro

Fixes the broken links on the donation page and also changes the text of the Ko-fi button from Patreon to Ko-fi. Have to get that bread.

Fix links on donation page

---

src/components/NavBar.astro

Added top, left and right styles for navbar dropdown's and centered them.

style(navbar): add top, left and right styles for navbar dropdown

---

src/pages/download.astro

fixes: https://github.com/zen-browser/www/issues/343

fix: Typo fix in download page

---

src/pages/mods/[...slug].astro
src/pages/mods/index.astro

comparison of the looks
old:
new:
old:
new:

feat: change borders on mod page to be consistent with current theming

---

src/components/NavBar.astro

Small NavBar improvements

---

src/components/Hero.astro

fix: adjust paddings for Hero

---

src/layouts/Layout.astro

Fixed annoying issue of flashbanging a user on page reload
https://github.com/user-attachments/assets/0fde9899-1fbd-4eff-a0ee-1521d68c929d
||
\V
https://github.com/user-attachments/assets/3c5022bc-66eb-48a3-bee5-435bee847917
P.S(Sorry for prettier, its formatting on save and i'm too lazy to disable it)

fix(flashbang): added a script to fix flashbang in page head

---

src/components/ReleaseNoteItem.astro

@NOCanoa resolved the conflict

feat: improved theming for release note accordions

---

src/components/ReleaseNoteItem.astro

this commit quickly fixes the accordion line lengths that was broken due to my previous PR.

fix: fixed line width for accordion border

---

src/pages/privacy-policy.astro

The privacy policy had a run-on sentence.

Grammar fix in Privacy Policy

---

src/components/ModsList.tsx

feat: removed focus outline on mod searchbar

---

src/release-notes/stable.json

Sorry, I'm not on my main PC rn so the commit isn't "Verified".

fix: adjusted grammar for release notes and fixed a typo

---

src/pages/download.astro

Revert "Fixed flatpak ID for new version `1.7b`"

---

src/pages/download.astro

Fixed flatpak ID for new version `1.7b`

---

src/components/Community.astro
src/components/Features.astro
src/components/Hero.astro
src/components/HomeExtras.astro
src/pages/mods/index.astro

Hey! This PR enhances the wording and grammar across Zen's website (particularly the marketing sections).
Summary of changes:
* [`src/components/Community.astro`](diffhunk://#diff-854b9520f5a2bd7fa23a827bf379837cab3f9200dea688e4ec06c626d8ba0772L35-R35): Updated text to correct capitalization and improve phrasing for better readability.
* [`src/components/Features.astro`](diffhunk://#diff-323106f71cb10f728ed3f8f6c5874a8c26b3bc20ca29402afcec8d2987729539L23-R28): Modified headings and descriptions to be more concise and clear.
* [`src/components/Hero.astro`](diffhunk://#diff-289237df7e7f2ebc1fa52e3aabba5f9a6599c1e53067fbf127b9d3a6b8943ab0L71-R71): Changed button label to better reflect the action.
* [`src/components/HomeExtras.astro`](diffhunk://#diff-c6fe497581650d27bc9fc343773b4efa9f36bb63a …

feat: enhance wording and grammar across site

---

src/layouts/Layout.astro

Hey! This PR makes minor improvements to SEO across Zen's website.
Summary of changes:
* Fixed the meta description tag. Previously, the description was too vague and not displayed by search engines due to not following proper SEO conventions. This change resolves that issue with a more accurate description.
* Injected schema onto homepage to improve SEO, as suggested by Google's SEO guide. Only injects schema if on homepage in order to avoid duplication across other pages.
If further adjustments are needed, feel free to let me know.

feat: improve SEO

---

src/pages/download.astro

removed continue button and remade the logic to work with onclick
https://github.com/user-attachments/assets/cf707536-3536-4bbd-9756-ec4eeb0cad89

(Download Page): Remove continue button 

---

src/components/ReleaseNoteItem.astro

Just a simple
```diff
- Github
+ GitHub
```

Correct word styling of GitHub

---

src/release-notes/stable.json

Minor spelling mistake

---

src/release-notes/stable.json

Grammar fixes for the latest release (and previous iterations of the word "URL bar").

Release grammar

---

src/components/ModsList.tsx
src/pages/mods/index.astro

Closes #507
This improves the mods page experience for ultra-wide monitors.

Update mods for larger monitor screen

---

src/components/download/ButtonCard.astro
src/components/download/DownloadScript.astro
src/components/download/PlatformDownload.astro
src/pages/download.astro
src/release-notes/stable.json
src/release-notes/whats-new.json

Release notes for 1.11b

---

src/pages/whatsnew.astro
src/release-notes/stable.json

Revert "Update to new version"

---

src/pages/whatsnew.astro
src/release-notes/stable.json

Revert "Revert "Update to new version""

---

src/components/Features.astro
src/components/Sponsors.astro
src/components/Video.astro
src/pages/index.astro

I've removed the intersection observer as it was causing performance issues on the site.

Improve the performance for low-end users

---

src/components/ThemeSwitch.astro

Prevent stale theme by resolving before toggle

---

.github/workflows/prbuildcheck.yml
src/components/download/ButtonCard.astro
src/components/download/DownloadScript.astro
src/components/download/PlatformDownload.astro
src/components/download/release-data.astro
src/pages/download.astro
src/utils/githubChecksums.ts

- Enhanced ButtonCard component to accept and display SHA-256 checksums.
- Updated PlatformDownload and release-data to include checksum information for each release.
- Modified DownloadScript to apply twilight mode to new checksum buttons.
- Adjusted download page to retrieve and display checksums dynamically.

feat(checksum): add checksum support to download components and update workflow

---

src/components/Features.astro

Made the videos sticky to prevent the component from hiding.
Closes #592
https://github.com/user-attachments/assets/0a3a443b-9282-4b0c-b644-4d46382c4a76

feat(sticky-features): make features videos sticky

---

src/components/download/DownloadScript.astro
src/components/download/PlatformDownload.astro

Hide Flathub download option for twilight.
Closes #453

fix(download): hide flathub download for twilight download page

---

src/components/Features.astro

This PR makes font size smaller for smaller screen.
Closes #613

fix(features): improve font size for features section title

---

src/components/ReleaseNoteListItem.astro

More vibrant and matching with the other text . While conveying a sense of emergency

Better color for the breaking title

---

.github/workflows/biome-autofix.yml

This PR adds a GitHub Actions workflow that runs on every push to master. If Biome style issues are detected, it auto-fixes them and creates or updates a pull request with the changes. This helps ensure code style consistency on the master branch automatically.

feat(biome): add a workflow to create pull request to automatically fix biome check issue

---

.github/workflows/biome-autofix.yml

I have added permission to workflow to allow pushing.

fix(workflow): add permissions for contents and pull-requests in biome-autofix.yml

---

src/i18n/ja/translation.json

This PR fixes and improves the Japanese translation in i18n to make it accurate and natural.

fix(i18n): improve Japanese translation

---

src/components/ModsList.astro

i made a little ui improvement in the zen mods page, the **sort buttons** felt a little off.
let me know your thoughts!

Sort button ui improvment in zen mods page

---

src/utils/i18n.ts

I have made sure it doesn't include i18n locales in getPath for external links.

fix(i18n): fix get path for external links

---

src/i18n/ja/translation.json

I have improved Japanese translation for feature section.

chore(i18n): update japanese translations for feature titles and descriptions

---

src/release-notes/stable.json

@mr-cheffy Let me know if you still want me to be adding punctuation (like ".") to the end of sentences for release notes

chore: Grammar changes
